### ISSUE TITLE
IndependentForwardProgress execution mode is undocumented

### ISSUE THREAD

**Issue by polarina** [KhronosGroup/SPIRV-Registry#12]
Appendix A.1 _"Changes from Version 0.99, Revision 31"_ says:
* Added *IndependentForwardProgress* Execution Mode (14271).

This is the only place within the specification where this execution mode is mentioned.

**Comment by johnkslang** [comment]
It was removed again in the next revision.

This is now logged in the changes in the upcoming next public revision SPIR-V 1.3.
