### ISSUE TITLE
OpRayQueryCommittedTypeKHR is mentioned in SPV_KHR_ray_query, but defined nowhere

### ISSUE THREAD

**Issue by khyperia** [KhronosGroup/SPIRV-Registry#128]
There's a bunch of phrases like this:

>  If _Intersection_ is **RayQueryCommittedIntersectionKHR**, there must be a current committed intersection (see _OpRayQueryCommittedTypeKHR_).

However, OpRayQueryCommittedTypeKHR isn't defined anywhere: grepping through this repository, the only mention is in the SPV_KHR_ray_query doc, in the above phrase. Googling, there are two hits, which are [the document](https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/KHR/SPV_KHR_ray_query.asciidoc) and [the raw html version](https://raw.githubusercontent.com/KhronosGroup/SPIRV-Registry/master/extensions/KHR/SPV_KHR_ray_query.html).

What is it? Where is it defined?

**Comment by Tobski** [comment]
FYI I believe that is supposed to refer to OpRayQueryGetIntersectionTypeKHR.

**Comment by johnkslang** [comment]
@dgkoch

**Comment by raunraun** [comment]
@dgkoch - github wont let me assign to you.

**Comment by dgkoch** [comment]
Pushed fix in #129 

@raunraun I've requested to join the KhronosGroup/SPIR team
