### ISSUE TITLE
How DebugEntryPoint refers to an entry point

### ISSUE THREAD

**Issue by AlexeySotkin** [KhronosGroup/SPIRV-Registry#133]
[DebugEntryPoint](https://github.com/KhronosGroup/SPIRV-Registry/blob/main/nonsemantic/NonSemantic.Shader.DebugInfo.100.asciidoc#DebugEntryPoint) instruction has an operand which should refer to an entry point:
> _Entry Point_ is the _\<id\>_ of the **OpEntryPoint** being described.

But [**OpEntryPoint**](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpEntryPoint) doesn't have the result id.

Perhaps the _Entry Point_ operand could refer to the result id of an **OpFunction** (which is also targeted by **OpEntryPoint**), but in this case it would be a forward reference.

@baldurk could you please clarify?

**Comment by baldurk** [comment]
That's my mistake forgetting that `OpEntryPoint` has no result ID. I think the simplest fix would instead be to refer to the `DebugFunction` instead. This can be tied to the entry point via `DebugFunctionDefinition` in the entry point's function, and would not be a forward reference (the `DebugEntryPoint` can be after the `DebugFunction`).

If you'd like me to make that change let me know.
