### ISSUE TITLE
help for offline deploy

### ISSUE THREAD

**Issue by hustcsxg** [KhronosGroup/SPIRV-Registry#135]
I want deploy this doc site in a offline scenario.
unlike other XXX-Registry repo (OpenCl-Registry ,OpenGL-Registry) , why not a index.php file in this repo.
when I visit link https://www.khronos.org/registry/SPIR-V/specs/ ,I saw the sub dir
1.0, 
1.1, 
1.2 
unified1

but subdir of this repo is 
CODE_OF_CONDUCT.md  extensions/  nonsemantic/  README.md

**Comment by hustcsxg** [comment]
@Khronoswebmaster @alan-baker

**Comment by Khronoswebmaster** [comment]
I believe you are looking for this repository https://github.com/KhronosGroup/Registry-Root-SPIR-V which is the backing repository for https://www.khronos.org/registry/SPIR-V/

**Comment by hustcsxg** [comment]
@Khronoswebmaster Page not found, the repo is private?

**Comment by Khronoswebmaster** [comment]
Our oversight on this repository, it is now public. If this satisfies your request, please feel free to close this issue.

**Comment by hustcsxg** [comment]
> Our oversight on this repository, it is now public. If this satisfies your request, please feel free to close this issue.

thx!
