### ISSUE TITLE
SamplerBuffer error in SPIR-V 1.6

### ISSUE THREAD

**Issue by georgeouzou** [KhronosGroup/SPIRV-Registry#139]
Hello all,

I compiled the following shader (simple.vert):
```
#version 450

layout(binding = 0) uniform samplerBuffer pos;

void main()
{
	gl_Position = texelFetch(pos, gl_VertexIndex);
}
```
with 

`glslc -Os --target-env=vulkan1.3 simple.vert`

and i get the following message:

> shaderc: internal error: compilation succeeded but failed to optimize: In SPIR-V 1.6 or later, sampled image dimension must not be Buffer
>   %17 = OpTypeSampledImage %16

I also compiled and optimized with glslangValidator/spirv-opt and i get the same error.
How can we use Vulkan's uniform texel buffers with Vulkan 1.3 and spirv 1.6?

**Comment by HansKristian-Work** [comment]
Use GL_EXT_samplerless_texture_functions and use textureBuffer. samplerBuffer is just goofy and glslang/shaderc should just emit plain ImageType for those.

**Comment by georgeouzou** [comment]
@HansKristian-Work thanks!
