### ISSUE TITLE
Asciidoctor tables are not rendered correctly

### ISSUE THREAD

**Issue by sjfricke** [KhronosGroup/SPIRV-Registry#155]
(This is not limited to `SPV_KHR_ray_tracing` but noticed it here first)

seems the `cols=` in the asciidoctor needs to be fixed in most the tables as they don't render correctly on Github

**Example:** 

[SPV_KHR_ray_tracing.html](https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_ray_tracing.html#_new_storage_classes)

![Screenshot from 2022-07-20 16-37-33](https://user-images.githubusercontent.com/9061055/179924664-c882937f-e926-40ea-8e88-83a8d941e792.png)

[SPV_KHR_ray_tracing.asciidoc](https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/KHR/SPV_KHR_ray_tracing.asciidoc)

![Screenshot from 2022-07-20 16-38-05](https://user-images.githubusercontent.com/9061055/179924789-268003cd-da96-475d-b3da-696cf2a66c5f.png)

**Comment by dgkoch** [comment]
I would say it's more accidental than anything that the asciidoctor manages to render directly at all, as the intended path is to use the HTML versions, but given that it *mostly* renders we probably should try to fix it.  Patches welcome? :-) 

(Ideally we'd also have a build system to actually build the html files in place as well, but that is currently left as an exercise to the reader and everyone does it a bit differently.)

**Comment by SamB** [comment]
> (Ideally we'd also have a build system to actually build the html files in place as well, but that is currently left as an exercise to the reader and everyone does it a bit differently.)

Even if the build system would build it, github won't serve it as text/html for security reasons.

**Comment by johnkslang** [comment]
I'm closing this, as the intended way to see an extension in rich text is to open the html version supplied for the extension, and we aren't tracking GitHub subset functionality in this space.
