### ISSUE TITLE
A clarification request for the OpQuantizeToF16 flush-to-zero semantics

### ISSUE THREAD

**Issue by wooyoungqcom** [KhronosGroup/SPIRV-Registry#197]
The spec https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_image_instructions says

>  If the magnitude of Value is too small to represent as a normalized 16-bit floating-point value, the result **may** be either +0 or -0.

It sounds like the result could be +0, -0, or anything else.  Is it the case ?
Or the spec wanted to say the result is either +0 or -0 and no other values are allowed ?

**Comment by gnl21** [comment]
It was discussed whether denorms should be allowed as a result here, but it was decided not to accept denorms here in Khronos bugzilla 14077. So I think this should be updated to say "must".

**Comment by wooyoungqcom** [comment]
Jeff Leger @ QC created a Vulkan issue https://gitlab.khronos.org/vulkan/vulkan/-/issues/3452 to discuss it there.

**Comment by jackohound** [comment]
I've opened [vulkan #3452](https://gitlab.khronos.org/vulkan/vulkan/-/issues/3452) to reflect what I understand to be the resolution.   The SPIR-V WG concluded that the client API should decide whether denorms are allowed.

**Comment by marty-johnson59** [comment]
Quick update - per WG call this morning, Vulkan is fine with this clarification.  It won't have any impact for them.

**Comment by bashbaug** [comment]
We've clarified this internally, by changing the spec text from "the result **may** be either +0 or -0" to "the result **must** be either +0 or -0", as described above.  This clarification will be in the next spec release.  Thanks!

**Comment by johnkslang** [comment]
The new revision of the specification has been published and fixed this, so closing.

See Revision 3 of SPIR-V 1.6 at https://registry.khronos.org/SPIR-V.
