### ISSUE TITLE
`DebugSource` `File` operand for generated shaders that only exist in memory

### ISSUE THREAD

**Issue by sakrel** [KhronosGroup/SPIRV-Registry#204]
The [`DebugSource`](https://github.com/KhronosGroup/SPIRV-Registry/blob/main/nonsemantic/NonSemantic.Shader.DebugInfo.100.asciidoc#DebugSource) instruction requires a `File` operand:
>File is an OpString holding the name of the source file including its full path.

What's the appropriate `OpString` for a shader that is generated on the go and only exists in memory?

Is it valid to pass `""` as the `File` operand if the `Text` operand is provided?
>Text is an OpString that contains text of the source program the SPIR-V module is derived from.

**Comment by bashbaug** [comment]
Hi @sakrel, just wanted to be sure you saw the comment above.  Will OpSource with an empty string work for you for shaders that only exist in memory?

**Comment by sakrel** [comment]
> Hi @sakrel, just wanted to be sure you saw the comment above. Will OpSource with an empty string work for you for shaders that only exist in memory?

Yes, DebugSource with an empty string works for me. I was just worried about running into tools that require DebugSource to always hold a full file path.

**Comment by bashbaug** [comment]
Great.  Is anything more needed from us, or can we close this issue?  Thanks!

**Comment by sakrel** [comment]
Issue can be closed. Thanks.
