### ISSUE TITLE
SPV_KHR_cooperative_matrix and optional operands

### ISSUE THREAD

**Issue by kuhar** [KhronosGroup/SPIRV-Registry#211]
`OpCooperativeMatrixLoadKHR` and `OpCooperativeMatrixStoreKHR` allow for 2 optional operands: stride and 'memory operand'.

When reading these two from a spir-v binary, how am I supposed to tell which of the two possible optional operands is provided? Should I assume that both are (always) either omitted or present at the same time?

**Comment by kpet** [comment]
_Stride_ must be provided for _Memory Operand_ to be provided. The following combinations are valid:
1. None of the optional operands are present.
2. _Stride_ alone is present.
3. _Stride_ and _Memory Operand_ are both present.

We will document this explicitly in the next revision of the specification.

**Comment by kuhar** [comment]
This makes sense, thanks Kevin!
