### ISSUE TITLE
RowMajor and ColMajor exclusivity constraint should be for structure members

### ISSUE THREAD

**Issue by polarina** [KhronosGroup/SPIRV-Registry#25]
Section 2.16.2, _Validation Rules for Shader Capabilities_, of the SPIR-V 1.3 Unified specification states:

> At most one of **RowMajor** and **ColMajor** Decorations can be applied to a structure type.

The RowMajor and ColMajor decorations are applied to structure members, not the structure type.

**Comment by johnkslang** [comment]
Yes, they should just be about what's allowed, the members, not the structure.

We're going to remove this line and instead put the restriction directly into the cells that describe the decoration semantics for RowMajor and ColMajor.

**Comment by johnkslang** [comment]
This is now fixed in the next revision of SPIR-V 1.4 and will be visible on its upcoming publication.

**Comment by johnkslang** [comment]
Revision 2 of SPIR-V 1.4 is now available in the [Khronos SPIR-V Registry](https://www.khronos.org/registry/spir-v/).
