### ISSUE TITLE
Github preview links on the SPIR-V registry page don't work.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/SPIRV-Registry#26]
Links like [these](http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/EXT/SPV_EXT_descriptor_indexing.html) from the SPIR-V registry page don't seem to work. I keep getting this error:

> TypeError: NetworkError when attempting to fetch resource.

I'm using the current version of Firefox.

It would probably be better to link directly to the [AsciiDoc source](https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/EXT/SPV_EXT_descriptor_indexing.asciidoc), since that renders properly in GitHub.

**Comment by johnkslang** [comment]
That link works fine for me. (I'm using Chrome.) Is it really due to the web browser though?

Does GitHub really correctly render all .asciidoc files?  Does it know when something is Asciidoctor instead?

**Comment by johnkslang** [comment]
Do you still see errors? Can anyone else reproduce this?

**Comment by NicolBolas** [comment]
I found out that it has something to do with NoScript (which I was sure was turned off). I still haven't found out how to fix it, but it's a local problem. Sorry about that.
