### ISSUE TITLE
OpPtrDiff with mix of untyped and typed pointers

### ISSUE THREAD

**Issue by ErikHogeman** [KhronosGroup/SPIRV-Registry#262]
Hi, the current spec language for OpPtrDiff is explicit about what happens if you have two typed pointers or two untyped pointers, but to me it's not too clear what the expectation is when mixing typed with untyped pointers. Would it be possible to clarify whether this is allowed or not and what is expected to happen in that case?

**Comment by alan-baker** [comment]
For reference, spirv-val currently requires the types of both operands to match. So both untyped or both typed. It would be possible to mix types if we treated it in the same manner as OpCopyMemory such that the result is based on the typed operand.
