### ISSUE TITLE
[Doc Bug] SPIRV-Headers updated OpDemoteToHelperInvocationEXT version number to 1.6

### ISSUE THREAD

**Issue by farzonl** [KhronosGroup/SPIRV-Registry#298]
https://github.com/KhronosGroup/SPIRV-Registry/blob/13711980b72448151d35980cc218c65c09784bec/extensions/EXT/SPV_EXT_demote_to_helper_invocation.asciidoc?plain=1#L48

Also their is a little bit of confusion as to whether this was written to mean 1.0 or 1.4. I think we should standardize to one version number.

This looks like a spec bug [OpDemoteToHelperInvocationEXT was updated to 1.6](https://github.com/KhronosGroup/SPIRV-Headers/blob/996c728cf7dcfb29845cfa15222822318f047810/include/spirv/unified1/spirv.core.grammar.json#L6475 ):

with this pr: https://github.com/KhronosGroup/SPIRV-Headers/pull/259

**Comment by bashbaug** [comment]
Hello!

The "revision" in the extension specification is the extension document revision.  For this extension, it is indicating that this is the first revision of the extension specification.  It is unrelated to a SPIR-V version.

Instead, the required SPIR-V version can usually be found in the "dependencies" section of the extension specification.  For this extension:

> This extension is written against the SPIR-V Specification, Version 1.4 Revision 1.
> This extension requires SPIR-V 1.0.

This means that the section numbers and other references in the extension specification are to the SPIR-V 1.4 specification, but the extension itself only requires SPIR-V 1.0.

Note that the functionality described by this extension became a core feature in SPIR-V 1.6, so you have a choice how to access it:

1. For SPIR-V versions before SPIR-V 1.6, you may access the functionality via the extension, by including `OpExtension "SPV_EXT_demote_to_helper_invocation"` in your SPIR-V module.
2. For SPIR-V 1.6, you may access some of the functionality without the extension, see the [change log](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_changes_from_version_1_5) for details:
     > SPV_EXT_demote_to_helper_invocation, with changes: Only [OpDemoteToHelperInvocationEXT](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpDemoteToHelperInvocation) was incorporated. Instead of using OpIsHelperInvocationEXT, modules should use Volatile loads of the HelperInvocation [built-in variable](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#BuiltIn).

Does this makes sense?  Thanks!

**Comment by farzonl** [comment]
This makes sense. My mistake in DXC we used `OpKill` unless the target was Vulkan 1.3 and SPIRV 1.6. So made assumptions about version numbers being off that is clearer now. Closing this issue.
