### ISSUE TITLE
Update SPIR-V Registry website

### ISSUE THREAD

**Issue by samuelig** [KhronosGroup/SPIRV-Registry#42]
[SPIRV-Registry repo](https://github.com/KhronosGroup/SPIRV-Registry) has more SPIR-V extensions listed than in [the registry](https://www.khronos.org/registry/spir-v/), specifically, we are missing links to:

```
SPV_INTEL_shader_integer_functions2
SPV_INTEL_fpga_loop_controls
SPV_EXT_fragment_shader_interlock
SPV_NV_shader_sm_builtins
```

**Comment by johnkslang** [comment]
These were the last 4, they as well as shader clock are now added.
