### ISSUE TITLE
OpVariable's type vs OpTypePointer's

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/SPIRV-Registry#57]
`OpTypePointer` takes a storage class. `OpVariable` takes an `OpTypePointer` and another storage class.

I don't see any validation rules regarding these two storage classes. In SPIR-V tools, I can see the following validation performed:

```C
  // SPIR-V 3.32.8: Check that pointer type and variable type have the same
  // storage class.
  const auto result_storage_class_index = 1;
  const auto result_storage_class =
      result_type->GetOperandAs<uint32_t>(result_storage_class_index);
  if (storage_class != result_storage_class) {
    return _.diag(SPV_ERROR_INVALID_ID, inst)
           << "From SPIR-V spec, section 3.32.8 on OpVariable:\n"
           << "Its Storage Class operand must be the same as the Storage Class "
           << "operand of the result type.";
  }
```

However, there's no such requirement in the spec at 3.32.8 under OpVariable (or anywhere else, searching for the validation language).

What's correct here?

---

Context: I'm looking at performing an in-place removal of an interface variable, and am wondering if I can just do this:

```
 %v2float = OpTypeVector %float 2
 %_ptr_Input_v2float = OpTypePointer Input %v2float
-%ToBeRemoved = OpVariable %_ptr_Input_v2float Input
+%ToBeRemoved = OpVariable %_ptr_Input_v2float Private
```

(and remove the variable from `OpEntryPoint` of course)

**Comment by johnkslang** [comment]
**OpVariable** does tie these storage classes together.  It says:

> *Storage Class* ... It must be the same as the *Storage Class* operand of the *Result Type*.

**Comment by ShabbyX** [comment]
Ok, I see that this line is missing from SPIR-V 1.0 spec, but it's there in 1.5.
