### ISSUE TITLE
Documentation on atomic operations against floats should reflect the specification

### ISSUE THREAD

**Issue by jhvst** [KhronosGroup/SPIRV-Registry#69]
Hope this is the right place to report this.

Background: https://github.com/KhronosGroup/SPIRV-Tools/issues/2128

Currently, the documentation on SPIR-V says to Atomic operations that `Result Type must be a scalar of integer type or floating-point type.` But, with the Vulkan memory model, you get an error per the linked SPIR-V tools issue. While the incompatibility might be clear to some, and it will eventually be for all that try it, it could be more clear right in the documentation.

**Comment by raunraun** [comment]
This is working as designed.  Client APIs can further restrict SPIR-V rules as the shader is executed in a client API's environment.  Vulkan is now allowing float atomics with this extension:

https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_shader_atomic_float.html
