### ISSUE TITLE
Universal validation rules seem to contradict OpenCL features

### ISSUE THREAD

**Issue by jenatali** [KhronosGroup/SPIRV-Registry#74]
The SPIR-V spec says:
```
No function can be targeted by both an OpEntryPoint instruction and an OpFunctionCall instruction.
...
The Linkage Attributes Decoration cannot be applied to functions targeted by an OpEntryPoint instruction.
```

However, OpenCL says:
```
It is just a regular function call if a __kernel function is called by another kernel function.
...
The extern storage-class specifier can only be used for functions (kernel and non-kernel functions) and global variables declared in program scope or variables declared inside a function (kernel and non-kernel functions).
```

The OpenCL conformance test suite includes separately-compiled and linked files where one contains an extern declaration of a kernel, and a call to it from with another entrypoint, and the other file contains the definition of that kernel.

In order to properly link them, the definition should have external linkage attributes. After linking, the resulting module will have two entry points, where one includes a call to another. Is the intention that the compiler and/or linker should produce two variations of the called kernel so as to not violate the SPIR-V spec? Or should the SPIR-V spec move those validation rules to the shader section?

**Comment by jenatali** [comment]
Further, perhaps validation should be added that indicates that any function marked as an entry point must have a function body, as entry point markers on declarations trips up the SPIRV-Tools linker.

**Comment by johnkslang** [comment]
>  Is the intention that the compiler and/or linker should produce two variations of the called kernel so as to not violate the SPIR-V spec?

Yes, front-ends should generate SPIR-V that satisfies the rule "No function can be targeted by both an OpEntryPoint instruction and an OpFunctionCall...".

**Comment by jenatali** [comment]
Unfortunately it looks like that was not a requirement for SPIR, meaning that using a pipeline of CL C -> SPIR -> SPIR-V, any logic to handle duplication of called kernels would need to live in the SPIRV-LLVM-Translator.

It also means that the translator would *always* need to generate two versions of a kernel, one as a plain function with external linkage (so it could be called by another module), and one as a kernel. That seems... onerous. I still think the spec is too strict here for OpenCL kernels.

**Comment by johnkslang** [comment]
It was considered the the interface to an entry point is a different kind of a thing than a normal function, and hence likely that some somewhere would have to deal with that.  The decision was to do it before generating SPIR-V.

I've seen similar things in other front ends too: the wrapping of an entry point adding a layer:

Source:

```
...entrypoint(...) { return entrypointBody; }
... foo() {  return entrypoint(...); }
```

Post transform:

```
...entrypointBodyFun(...) { return entrypointBody; }
...entrypoint(...) { return entrypointBodyFun(...); }
...foo() { return entrypointBodyFun(...); }
```

Of note, there are not two copies of the entry-point body, just one.

**Comment by jenatali** [comment]
Hm, that seems more reasonable, yeah. The only problem then is picking a unique name mangling for the implementation function.

I think that might be beyond my capabilities for modifying the LLVM-SPIRV-Converter, but that would be the correct change to make I guess. Any kernel definition should be converted into an entry point wrapper, and an implementation with exported linkage. Any kernel declaration should be converted into just a declaration of the non-entry-point implementation.

**Comment by jenatali** [comment]
I think we can close this now. The entrypoint wrapper in the SPIRV-LLVM-Translator proves that this spec rule is possible to keep even though CL would seem to require violating it.
