### ISSUE TITLE
ImageMSArray should require the image to be arrayed

### ISSUE THREAD

**Issue by polarina** [KhronosGroup/SPIRV-Registry#79]
Compare the wording for `StorageImageMultisample` and `ImageMSArray`.
> **StorageImageMultisample**
> Uses multi-sample images for non-sampled images

> **ImageMSArray**
> An _MS_ operand in `OpTypeImage` indicates multisampled, used without a sampler.

From their descriptions alone one may believe that the two capabilities are equivalent. The `ImageMSArray` capability should require the `Arrayed` operand in `OpTypeImage` to be set too.

**Comment by gnl21** [comment]
I think that this has been resolved in the newest version of the spec.
