### ISSUE TITLE
SPV_NV_cooperative_matrix extension proposal

### ISSUE THREAD

**Issue by dkhaldi** [KhronosGroup/SPIRV-Registry#82]
There are some issues with the current SPV_NV_cooperative_matrix extension proposal:	
- ColumnMajor should be more than a Boolean that states row or column major layout since there are more layouts than just these two. At least right now, in AMX, we should be able to specify the VNNI format that consists of packing small precision data into 32 bits to be contiguous in memory. We can call this layout "word_packed". 
- Making rows and columns constants is too restrictive. We should allow both constant and variables. While GPUs require constant values for diverse performance reasons, AMX and CPU hardware has no such restriction.
- We should not limit the subgroup concept to the NVIDIA size of 32. Subgroup size is the simd size and can be dictated by the user. The implementation will specify whether it supports that simd size or not. But from the interface perspective, we should not have such restriction.  
- We should make sure the interface is extendable to include other operations such as transpose transform.

**Comment by kpet** [comment]
Thank you for the feedback. This is valuable input to some in-progress discussions around the evolution of that extension (cc @jeffbolznv).

**Comment by dkhaldi** [comment]
One more question, what is the SPIRV representation to be used for matrix initialization such as:
void fill_fragment(fragment<...> &a, const T& v);

Also, is there a current discussion or a work group to track progress of the cooperative matrix proposal?

**Comment by jeffbolznv** [comment]
> One more question, what is the SPIRV representation to be used for matrix initialization such as:
> void fill_fragment(fragment<...> &a, const T& v);

This can be done with OpCompositeConstruct with `v` as the sole constituent operand.

> Also, is there a current discussion or a work group to track progress of the cooperative matrix proposal?

Nothing public, but since you work at a Khronos member company you could potentially get involved in the private Khronos meetings.
