### ISSUE TITLE
Extension SPV_AMD_gpu_shader_half_float references SPIR-V 1.10

### ISSUE THREAD

**Issue by polarina** [KhronosGroup/SPIRV-Registry#9]
The `SPV_AMD_gpu_shader_half_float` extension references SPIR-V 1.10. This version of SPIR-V does not exist (yet).

> This extension is written against Revision 1 of the version 1.10 of the SPIR-V Specification.

https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/AMD/SPV_AMD_gpu_shader_half_float.asciidoc#dependencies

**Comment by johnkslang** [comment]
SPIR-V 1.1 exists, and is now just part of the unified specification. It should be 1.1, not 1.10 though.
