### ISSUE TITLE
PrimitiveId usage

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/SPIRV-Registry#95]
According to the Vulkan spec, `PrimitiveId` is legal in fragment shaders:
```
VUID-VkGraphicsPipelineCreateInfo-pStages-00740
If pStages includes a fragment shader stage and a geometry shader stage, and the
fragment shader code reads from an input variable that is decorated with PrimitiveID,
then the geometry shader code must write to a matching output variable, decorated with
PrimitiveID, in all execution paths
```

According to the latest SPIRV spec, however, the decoration requires one of `Geometry, Tessellation, RayTracingNV, RayTracingKHR, MeshShadingNV`, none of which (to my knowledge) should be used by the fragment stage.

Which specification is correct in this case, or have I missed something?

**Comment by gnl21** [comment]
It is legal in fragment shaders, but the Vulkan spec also says:
> VUID-PrimitiveId-Fragment-04333
If Fragment Execution Model contains a variable decorated with PrimitiveId either the
Geometry or Tessellation capability must also be declared

so I think that the SPIR-V is technically correct, if strange and potentially misleading. Probably the right fix here is to clarify that those capabilities sometimes mean using features that are in some sense tessellation or geometry related but not actually in those stages.

**Comment by raunraun** [comment]
SPIR-V working group has decided to not add any further clarification on this topic.  The comment above from @gnl21 is correct.
